### ISSUE TITLE
[JOSS-Review][Question] What is meant by `application` in the Methodology section of the paper

### ISSUE THREAD

**Issue by Manvi-Agrawal** [souradipp76/ReadMeReady#10]
Could you please clarify what is meant by `application` term used in the Methodology section of the paper?  Is there a website, app, etc which provides users to enter the project details?
> The application prompts the user to enter the project's name, GitHub URL, and select the desired model from the following options:

### Context
Part of https://github.com/openjournals/joss-reviews/issues/7489

**Comment by souradipp76** [comment]
Hi @Manvi-Agrawal, the project has a CLI application. You can follow the installation and CLI usage instructions given in [README.md](https://github.com/souradipp76/ReadMeReady/blob/main/README.md#installation) and run the CLI app using the `readme_ready` command. The app will prompt you to select the open-source model and other parameters.
