### ISSUE TITLE
[JOSS-Review][Question] Hardware Requirements?

### ISSUE THREAD

**Issue by Manvi-Agrawal** [souradipp76/ReadMeReady#12]
What are the hardware requirements to run `readme-ready` framework?

### Additional Context
As part of https://github.com/openjournals/joss-reviews/issues/7489

**Comment by souradipp76** [comment]
@Manvi-Agrawal, the hardware requirements for the package depend on the open-source large language models used for text generation. Some of the models are large and resource-intensive so 4-bit quantization techniques have been applied on those models by default. For our experimentation and tests, we used 1 × NVIDIA Tesla V100 with 16GB of GPU memory. Thus a 16GB GPU is ideal for running the framework.

**Comment by Manvi-Agrawal** [comment]
[Non-Blocking] How about adding `1 × NVIDIA Tesla V100 with 16GB of GPU memory` was used for experimental results in the methodology section?

**Comment by souradipp76** [comment]
I have added this detail in the methodology section as suggested.
