### ISSUE TITLE
[JOSS-Review][Question] How to use framework for non OpenAI models?

### ISSUE THREAD

**Issue by Manvi-Agrawal** [souradipp76/ReadMeReady#8]
@souradipp76 , I am trying to install and use this python package. Could you please provide more details in the README on how to run a non OpenAI model since the main USP of this project is to have a framework for README generation to avoid costly OpenAI API pricing.
![image](https://github.com/user-attachments/assets/1fca0c8b-84dd-41e8-8a88-c2867bc8500f)

### Additional Context
As part of https://github.com/openjournals/joss-reviews/issues/7489

**Comment by souradipp76** [comment]
Hi @Manvi-Agrawal, you can follow the installation and CLI usage instructions given in [README.md](https://github.com/souradipp76/ReadMeReady/blob/main/README.md#installation). For using non-OpenAI models, set a dummy value for OPENAI_API_KEY env variable and run the CLI app using the `readme_ready` command. The app will prompt you to select the open-source model and other parameters.
